### PR TITLE
Updated logic, added support for multiple includes, modified formatting

### PR DESCRIPTION
**Pull request by JoinedSenses**
Theres a bug in current version on line 555 due to typing var name return_type as returntype.

This PR modifies general logic for line processing. It adds support for multiple include directories. Formatting has also been updated to better follow python standards.

### CODE REVIEW

**Comment by ppalex7** [comment]
@JoinedSenses could you resolve merge conflicts, please?

**Comment by JoinedSenses** [comment]
Sure, fixed. Since I am still supporting this package and working on features that were added to sourcepawn, would you be comfortable with granting me write access to this repo so I dont have to bug you with changes? If not, I understand.

**Comment by ppalex7** [comment]
Well, it will be more convenient! I closed my tf2 server a few years ago and have no active developing since.

Added you as collaborator to this repo.

**Comment by ppalex7** [comment]
I think there is still one typo in code - ```include_re```(line 255), not defined ```includes_re```.

Could you fix them too, and tag new version in repo?

**Comment by JoinedSenses** [comment]
the typo has been fixed - is there any versioning in the repo? I see here: https://packagecontrol.io/packages/SourcePawn%20Completions it shows version 1.3.0

**Comment by ppalex7** [comment]
Yes. Version in Package control based on [repository tags](https://github.com/ppalex7/SourcePawnCompletions/releases)

**Pull request merged**
